### ISSUE TITLE
Is there any issue capturing the "registry" parameter?

### ISSUE THREAD

**Issue by cusspvz** [drone-plugins/drone-docker#101]
I've configured a drone 0.5 environment and adapted a build config to check if it works.

Unfortunately, there is a issue on publishing a docker image. At first glance, it seems this plugin isn't gathering correctly the registry host. (or if it is, maybe it is not accepting it?)

Here's the configuration I've used.

```yaml
  publish_docker_image:
    image: plugins/docker
    registry: **secret**
    username: **secret**
    password: **secret**
    email: **secret**
    repo: findhit/frontend
    tag: ${DRONE_COMMIT_BRANCH##deployed/}-${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - deployed/*
```

Here's the output tail of where it fails:

```
Successfully built 7455cacb8b7a
+ /usr/local/bin/docker tag f03090ce1508a09b06ee2e14f27fb0588710319f findhit/frontend:staging-f03090ce
+ /usr/local/bin/docker push findhit/frontend:staging-f03090ce
The push refers to a repository [docker.io/findhit/frontend]
137ad23e6a22: Preparing
e2fb26a41375: Preparing
68c92a11771f: Preparing
5e01ccb60705: Preparing
cb91c689a4ac: Preparing
e5d83b6ea03c: Preparing
df411e57e548: Preparing
4fe15f8d0ae6: Preparing
e5d83b6ea03c: Waiting
df411e57e548: Waiting
4fe15f8d0ae6: Waiting
denied: requested access to the resource is denied
exit status 1
```

If you noticed it, it is trying to push it under **docker.io/findhit/frontend** instead of provided registry.

Is there any chance I can help on this?
Thanks.
