### ISSUE TITLE
Custom port for Docker Registry

### ISSUE THREAD

**Issue by cgebe** [drone-plugins/drone-docker#112]
```
  deploy_develop:
    image: plugins/docker
    repo: 127.0.0.1/cgebe/project-develop
    registry: 127.0.0.1:5000
    tags: 
      - latest 
      - ${DRONE_COMMIT_SHA:0:8}
    when:
      status: success
      branch: develop
```

port is always substituted with port 80.

```
The push refers to a repository [127.0.0.1/cgebe/project-develop]
Put http://127.0.0.1/v1/repositories/cgebe/project-develop/: dial tcp 127.0.0.1:80: getsockopt: connection refused
```
