### ISSUE TITLE
implement version file parameter

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-docker#116]
We previously implemented a temporary workaround to programmatic image tags by loading an environment file. I would like a more permanent solution based on some previous suggestions, specifically using a file to load tags.

We could add a `tag_file` field to the yaml that points to a version file:

```diff
pipeline:
  docker:
    image: plugins/docker
    username: kevinbacon
    password: pa55word
    email: kevin.bacon@mail.com
    repo: foo/bar
    tags: latest
+   version_file: VERSION
```

The tag is read from the file. Example version file:

```
17.3
```

The version file will not override the tags attribute. Instead it should be appended to the tag list.

This means we should remove the prior workaround:

```diff
func main() {
-	// Load env-file if it exists first
-	if env := os.Getenv("PLUGIN_ENV_FILE"); env != "" {
-		godotenv.Load(env)
-	}
```

**Comment by bradrydzewski** [comment]
@jmccann I know you and I discussed this, and you helped implement the env file as a temporary workaround. I think this solution (your original suggestion) is probably the best permanent path forward. Let me know thoughts

**Comment by jmccann** [comment]
Can we have both?

I like `version_file` to make it easier to do dynamic versioning for the 90%.  But I'm going to be honest and say I'm using `env_file` for some more advanced stuff now.  Especially recently.

I've created an internal plugin-pipeline to build/publish plugins from source.  I'm doing matrix of builds for each plugin.  I'm configuring how to build the docker using `env_file` like:

```
pipeline:
  docker_args:
    image: alpine:3.4
    commands:
      # Make sure plugin.json exists for plugin
      - "if [ ! -f ${PLUGIN_PATH}/plugin.json ]; then exit 1; fi"

      # Install jq to parse json from command line
      - apk update
      - apk add jq

      # Generate PLUGIN_ vars
      - export NAME=$(jq ."name" ${PLUGIN_PATH}/plugin.json -r)
      - export PLUGIN_REPO=jmccann/$NAME
      - export PLUGIN_DOCKERFILE=${PLUGIN_PATH}/repo/Dockerfile
      - "export PLUGIN_TAGS=$(jq '.\"tags\" | join(\",\")' ${PLUGIN_PATH}/plugin
.json -r)"
      - export PLUGIN_CONTEXT=${PLUGIN_PATH}/repo

      # Create env file
      - env | grep PLUGIN_ > env
      - cat env

  public_docker:
    when:
      event: push
      branch: master
      local: false
    image: plugins/docker
    env_file: env

matrix:
  PLUGIN_PATH:
    - plugins/github.com/jmccann/drone-chef-supermarket
    - plugins/github.com/athieriot/drone-artifactory

```

**Comment by jmccann** [comment]
OK, so @bradrydzewski keyed me in to a way better way to do what I was trying to do.  Which maybe shows how having `env_file` support can lead to overcomplicated solutions ... 

```yaml
pipeline:
  public_docker:
    when:
      event: push
      branch: master
      local: false
    image: plugins/docker
    repo: jmccann/${P_NAME}
    context: ${P_PATH}
    tags: ${P_TAGS}
    dockerfile: ${P_PATH}/Dockerfile

matrix:
  include:
    - P_NAME: drone-chef-supermarket
      P_PATH: plugins/github.com/jmccann/drone-chef-supermarket
      P_TAGS: latest,1,1.0
    - P_NAME: drone-artifactory
      P_PATH: plugins/github.com/athieriot/drone-artifactory
      P_TAGS: latest,1,1.0
```
