### ISSUE TITLE
Plugins fails due to most recent commit (docker system prune -f)

### ISSUE THREAD

**Issue by anorsich** [drone-plugins/drone-docker#117]
A few days ago [following commit](https://github.com/drone-plugins/drone-docker/commit/661ee5d652475e6be6812f80156495d778d64173) was merged into the docker plugin. Our deployment pipeline started to fail right after. 

I might be wrong, but it looks like `prune` also removes the volume where source code is mounted. That the reason for two errors: 

1. ` unable to get absolute path to Dockerfile: getwd: no such file or directory`
2.  `error_outlineERROR: get 89da68151e049a5047a107fb14d0930ad62035949305a723bcfab180c9f2dd35: volume not found`

One important note is that we mount `docker.sock` to use docker cache and gain some speed in exchange to isolation. 

Here is how the step looks like: 

```
  publish-lib-docker:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: magpieapp/lib
    tags:
      - "${DRONE_BRANCH}_${DRONE_COMMIT}"
      - latest
    dockerfile: ./shared/Dockerfile
    context: ./shared/
```

We use Docker v1.13.1. 

Here are details I can see in build output:

```
Live Restore Enabled: false
+ /usr/local/bin/docker system prune -f
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
Deleted Containers:
9360938c57f3856d5b95e728448c5e0c650ecb0085d67a4d9a4e26f6d3a03b1a
Deleted Volumes:
0757a2a51c2c8113f9ecf4614b5e42119334167b8ef9a8213e86160175a3de3b
89da68151e049a5047a107fb14d0930ad62035949305a723bcfab180c9f2dd35
92d493025cc5de41ab78a327f4f9a9585cf7ba4d33256d5dbb3252bacc17e841
Total reclaimed space: 27.17 MB
+ /usr/local/bin/docker build --rm=true -f ./shared/Dockerfile -t 5812553801c8841d99b3359f37b7f878e8ff866d ./shared/ --pull=true
unable to prepare context: unable to get absolute path to Dockerfile: getwd: no such file or directory
```

Here are details I can see in the build header: 

```
error_outlineERROR: get 89da68151e049a5047a107fb14d0930ad62035949305a723bcfab180c9f2dd35: volume not found
```

We had to fall back to the version 1.12 of plugins/docker to make it work again.
