### ISSUE TITLE
[FEATURE] Dry Run Option in .drone.yml 

### ISSUE THREAD

**Issue by Lerentis** [drone-plugins/drone-docker#127]
Hello there,

i wanted to use this drone plugin just to build a few images, but only to push them to a registry on a tag. I have seen that there already is a dry run flag in the code, but it does not seem to be possible to set this flag from a drone.yml file. this would be a great addition to have the possibility 

cheers

**Comment by Lerentis** [comment]
damn sorry i should have read the closed comment section as well, that this was already suggested and denied :/
https://github.com/drone-plugins/drone-docker/issues/108

**Comment by bradrydzewski** [comment]
You can use two different steps for this. The first step has the `dry_run` attribute set and will only execute for push events. The second step will only execute for tag events and will publish.

```
pipeline:
  build:
    image: plugins/docker
    repo: foo/bar
    dry_run: true
    when:
      event: [ push, pull_request ]

  build_publish:
    image: plugins/docker
    repo: foo/bar
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
```

> I have seen that there already is a dry run flag in the code, but it does not seem to be possible to set this flag from a drone.yml file

You can in fact set this flag from the .drone.yml file (example below)

> damn sorry i should have read the closed comment section as well, that this was already suggested and denied

Just to clarify we did not deny the use of dry run. That issue wanted to make images available for multiple steps which simply was not possible because this plugin uses dind.
