### ISSUE TITLE
build_args doesn't support spaces

### ISSUE THREAD

**Issue by dolanor** [drone-plugins/drone-docker#128]
It seems that the parsing of StringSlice from urfave/cli split by spaces and not by '\n', therefore, a definition as such doesn't work
```
build_args:
  - "MYENV=lala it is great"
```

I tried
```
build_args:
  - "MYENV='lala it is great'"
```
or

```
build_args:
  - 'MYENV="lala it is great"'
```
and none of them worked. I didn't have time enough to fix it or to check how to do it. But I guess that it might be a big change if we impact urfave/cli.

**Comment by bradrydzewski** [comment]
> It seems that the parsing of StringSlice from urfave/cli split by spaces and not by '\n', therefore, a definition as such doesn't work

I cannot repeat this issue. I am using the following yaml:

```
pipeline:
  build:
    image: plugins/docker
    dry_run: true
    repo: foo/bar
    build_args:
      - FOO=BAR
      - BAZ=BOO BOO
```

and I see the following output in my build:

```
+ /usr/local/bin/docker build --pull=true --rm=true -f Dockerfile -t 573a2d2d6f3f0b15b25a0d669fc91ad22492f59f . --build-arg FOO=BAR --build-arg BAZ=BOO BOO
```

You can see two separate `--build-arg` items including the item with a space in the string.

**Comment by bradrydzewski** [comment]
also just to be sure, I tested with the example that was provided

```
pipeline:
  build:
    image: plugins/docker
    dry_run: true
    repo: foo/bar
    build_args:
      - "MYENV=lala it is great"
```

and I saw this output:

```
+ /usr/local/bin/docker build --pull=true --rm=true -f Dockerfile -t dc339e79b3f1d85d05df3658e383f026189d2ddb . --build-arg MYENV=lala it is great
```

So at this time I am closing this issue as unable to repeat using the example given in the issue request. If you can provide a sample yaml that can be used to consistently reproduce an issue we can re-open.
