### ISSUE TITLE
Test Before Publish

### ISSUE THREAD

**Issue by jamrizzi** [drone-plugins/drone-docker#130]
Is there a way to test the docker container after it is built, but before it is published. I have a postman collection I want to run over it. I already build the drone plugin for running the postman collection.

https://github.com/jamrizzi/drone-postman
https://hub.docker.com/r/jamrizzi/drone-postman

**Comment by bradrydzewski** [comment]
There is not, the scope of this plugin is to build and publish an image only. If you would like to test images you have the option to create your own custom plugin (you can fork this one or start from scratch) or you can avoid plugins and interact directly with the host machine docker daemon, which is the most flexible option.

**Comment by jamrizzi** [comment]
Thanks, I figured out how to do it :)

**Comment by gtaylor** [comment]
@jamrizzi What did you end up doing?

**Comment by jamrizzi** [comment]
Here's the whole config file. The trick was to build the container with Docker (while caching it). Then I could run tests on it. Then when I used the official Drone Docker plugin, it would pull the container from cache (so it wouldn't rebuild it), and then it would publish it.

```yml
pipeline:
  restore_cache:
    image: drillster/drone-volume-cache:latest
    restore: true
    mount:
      - /var/lib/docker
    volumes:
      - /tmp/cache:/cache
    when:
      event: push
      branch:
        - master
        - dev

  build:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t promanager/pro-manager:${DRONE_REPO_BRANCH/master/latest} .
    when:
      event: push
      branch:
        - master
        - dev

  promanager:
    image: promanager/pro-manager:${DRONE_REPO_BRANCH/master/latest}
    group: test
    when:
      event: push
      branch:
        - master
        - dev

  pause:
    image: busybox:latest
    commands:
      - sleep 5
    when:
      event: push
      branch:
        - master
        - dev

  postman:
    image: jamrizzi/drone-postman:latest
    group: test
    collection: 'https://www.getpostman.com/collections/1d9b160b5c1d563721ff'
    when:
      event: push
      branch:
        - master
        - dev

  publish:
    image: plugins/docker:1.3
    username: ${DOCKER_USERNAME}
    email: ${DOCKER_EMAIL}
    password: ${DOCKER_PASSWORD}
    dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: promanager/pro-manager
    tag: ${DRONE_REPO_BRANCH/master/latest}
    secrets:
      - docker_username
      - docker_email
      - docker_password
    when:
      event: push
      branch:
        - master
        - dev

  deploy:
    image: majest/drone-rancher:latest
    rancher_url: https://orchestration.spinach.cafe
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    stack: ${DRONE_REPO_BRANCH/master/prod}-promanager
    service: pro-manager
    docker_image: ${DRONE_REPO_BRANCH/master/latest}
    timeout: 300
    confirm: true
    secrets:
      - rancher_access_key
      - rancher_secret_key
    when:
      event: push
      branch:
        - master
        - dev

  rebuild_cache:
    image: drillster/drone-volume-cache:latest
    rebuild: true
    mount:
      - /var/lib/docker
    volumes:
      - /tmp/cache:/cache
    when:
      event: push
      branch:
        - master
        - dev

services:
  db:
    image: mongo:latest
    when:
      event: push
      branch:
        - master
        - dev
```

**Comment by captn3m0** [comment]
Here's a version that works with this plugin and without mounting the docker socket:

```yaml
pipeline:
  restore-cache:
    image: plugins/drone-s3-cache
    restore: true
    mount:
      - docker_cache
    endpoint: http://bucket.s3-ap-south-1.amazonaws.com
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
      - aws_region
    when:
      event: push
  build:
    image: plugins/docker
    repo: org/repo
    secrets: [docker_username, docker_password, git_token]
    build_args_from_env: [git_token]
    environment:
    # Makes sure that the docker volume cache survives this run
      PLUGIN_STORAGE_PATH: /drone/src/github.com/org/repo/docker_cache
    tags: ${DRONE_COMMIT_SHA}
    compress: true
    # Ensures that docker prune is called at the end of the build
    docker:
      purge: false
    when:
      status: [success]
      event:
        exclude: [deployment]
        include: [push]
  rebuild-cache:
    image: plugins/drone-s3-cache
    endpoint: http://bucket.s3-ap-south-1.amazonaws.com
    secrets:
      - aws_region
      - aws_access_key_id
      - aws_secret_access_key
    rebuild: true
    mount:
      - docker_cache
    when:
      event: push
```

The trick is in three things:

1. Pass the `PLUGIN_STORAGE_PATH=/drone/src/github.com/org/repo/docker_cache` which forces the docker_cache to be passed between all pipeline steps
2. You have to make sure that your `.dockerignore` contains `docker_cache`, otherwise `docker build` will take ages because of the huge context to pass.
3. Setting `docker.purge=false` which forces the `docker system prune` from being run  within this plugin.
