### ISSUE TITLE
pipeline step cannot authenticate using this plugin

### ISSUE THREAD

**Issue by tomhaj** [drone-plugins/drone-docker#156]
Hi!

I've a problem. We have defined step to build docker image and publish it using your plugin. But all time we get an error
```bash
time="2017-10-22T09:06:36Z" level=fatal msg="Error authenticating: exit status 1"
```

Million times we check user and password. They are correct. Username & password also not contain any special characters, only numbers and letters.

Our pipeline definition looks like this:
```yml
pipeline:
    .....
    build:
        image: plugins/docker
        repo: xxxx.domain.com/sample
        username: xxxxx
        password: xxxxx
        registry: xxxx.domain.com
        tags: master
        when:
            branch: master
            status: success
```

and also not work with this:
```yml
pipeline:
    .....
    build:
        image: plugins/docker
        repo: xxxx.domain.com/sample
        secrets: [docker_username,docker_password]
        registry: xxxx.domain.com
        tags: master
        when:
            branch: master
            status: success
```

**Comment by tomhaj** [comment]
This can be helpful:
```bash
time="2017-10-22T09:38:23.585803056Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://xxxx.domain.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2017-10-22T09:38:53.587622280Z" level=info msg="Error logging in to v1 endpoint, trying next endpoint: Get https://xxxx.domain.com/v1/users/: dial tcp 145.239.81.14:443: i/o timeout" 
time="2017-10-22T09:38:53.588728889Z" level=error msg="Handler for POST /v1.29/auth returned error: Get https://xxxx.domain.com/v1/users/: dial tcp 145.239.81.14:443: i/o timeout" 
time="2017-10-22T09:38:53Z" level=fatal msg="Error authenticating: exit status 1" 
```

**Comment by tboerger** [comment]
IMHO the error message from the docker client is pretty clear, it's running into a timeout while trying to connect to your registry.

**Comment by tomhaj** [comment]
I found solution without using that plugin:
```yml
pipelines:
    build:
        image: docker
        secrets: [docker_username,docker_password]
        commands:
            - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD example-registry.com
            - docker build -t example-registry.com/sample:master -f docker-build/Dockerfile .
            - docker push example-registry.com/sample:master
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        when:
            branch: master
            status: success
```
We can close this issue. Thanks for help

**Comment by mc388** [comment]
I have the same issue but using an other image could not be the solution.

**Comment by Johnsel** [comment]
I seem to have solved the issue by removing a dash from the repo name. That is to say:

repo: docker.xyzcompany.com/something-project/something 
vs not working
repo: docker.xyzcompany.com/something-project/something-project

can't say for certain though, it may have been an issue in that repository, on the registry end, I could not dig up any meaningful logs

**Comment by anarcher** [comment]
I guess that I have some issue. I think it is kind of network issue.

```
time="2018-04-12T00:03:06.209232517Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://registry.example.com/v2/: dial tcp 172.18.0.2:443: getsockopt: connection refused"  
```
In my case, I works  connecting the registry  in drone host. Does it have some network condition in plugins/docker? 

Thanks

**Comment by muzea** [comment]
Also encountered this problem. When I saw the code here
https://github.com/drone-plugins/drone-docker/blob/master/docker.go#L161-L171

I realized that the username here is not my email, so the problem is solved.

**Comment by mingslife** [comment]
An insecure industry can also cause this problem. According what it say in [Parameter Reference](http://plugins.drone.io/drone-plugins/drone-docker/#parameter-reference), just set the **insecure=true** in the settings of this plugins can solved this problem.

The key part of my drone configuration is following:

```yaml
steps:
- name: build
  image: plugins/docker
  settings:
    registry: xxx.com:15000
    username: admin
    password: 123456
    repo: xxx.com:15000/hello
    tags: latest
    insecure: true
```
