### ISSUE TITLE
Docs don't mention caching at all

### ISSUE THREAD

**Issue by mvdan** [drone-plugins/drone-docker#172]
They used to - noticed some commits and previous issues - but the current docs page doesn't mention them at all: http://plugins.drone.io/drone-plugins/drone-docker/

What is the recommended way to handle this? Even if the docs just covered the basic case of "I don't want to re-download my `FROM` image every single time", that would be a great step forward.

**Comment by mvdan** [comment]
One way that would be interesting for it to work is if the plugin checked if the host's Docker already had that image. That is, using the host's image cache as a read-only cache.

That way, if I'm building my deployment images on an Alpine base, all I would need to do for them to be faster is make sure that the base image is cached in the Drone Agent host.

**Comment by tboerger** [comment]
Today you can use some drone cache plugins for that if you change the docker storage path, but don't use the s3-cache plugin, looks like this won't work for it now.

**Comment by mvdan** [comment]
Making it work with the regular caching plugins seems like a good idea. An example in the docs would still be great, though.

**Comment by Sharsie** [comment]
We really tried hard to implement caching using a plugin, maybe you can correct me if we went wrong about it, but here's what we tried and failed at each and every one of the attempts (resolution at the end):

1) Backup/Restore of `docker/image` and `docker/{aufs/overlay2}`
In this case the cache worked, however with each new build, we kept getting more and more layers and diffs which were not deleted after `docker system prune -f` After a couple of hundred builds we ended up with cache of several GB for each one of the projects (php apache2 based images with additional 200mb of changing data)
This actually resulted in a major slowdown of builds where the cache restore/rebuild steps would take a few times longer than if the cache was not used at all

2) Using a docker service
This is fine and dandy until the point where we could not start the docker service and `plugins/docker` with the same `--data-root/--graph`, which for obvious reasons did not work. The idea was to use docker service for save/loading of cached image so the layers are available for `plugins/docker` step. If different `--data-root/--graph` was used then we could not share the layers between the docker service and `plugins/docker`.
So this led us to drropping the `plugins/docker` image for publishing and using own `docker` image with customized build steps and `--cache-from` parameter.
This actually worked, but it was such a dirty solution that we did not really want to go that way and started thinking about PR for `plugins/docker` to have this implemented correctly.


And this is where we found out there is a PR #151 from september which effectively solves the problem. However, there are still a couple of things that might need further discussion before it is finally merged.

**Comment by Depado** [comment]
I'm also interested in this as the plugin keeps pulling the whole images every time, which is honestly kind of long for multi-stage builds that uses 2 or 3 different images.

I have no idea how to use the caching mechanism for this unfortunately and can't seem to find a proper solution in the issues.

**Comment by arno01** [comment]
I would like to share with my steps which allowed me to use the docker image caching in Drone CI without the need of using _trusted_ nor _privileged_ git repository options.

To enable docker image caching all you need is:

- ``DRONE_VOLUME=/tmp/drone-cache:/cache`` drone-server variable;
- ``storage_path: /drone/docker`` and ``use_cache: true`` parameters for ``plugins/docker`` job;
- ``drillster/drone-volume-cache`` of course ;-)

## docker-compose.yml

```
version: '3'

networks:
  oasis: {}

services:
  drone-server:
    restart: unless-stopped
    image: drone/drone:0.8
    networks:
      - oasis
    volumes:
      - /srv/data/drone/lib/drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=false
      - DRONE_ADMIN=REDACTED
      - DRONE_HOST=https://REDACTED
      - DRONE_SECRET=REDACTED
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=https://REDACTED
      - DRONE_GITEA_PRIVATE_MODE=true
      - DRONE_VOLUME=/tmp/drone-cache:/cache

  drone-agent:
    restart: unless-stopped
    image: drone/agent:0.8
    networks:
      - oasis
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=REDACTED
```

## .drone.yml

```
pipeline:
  restore_cache:
    image: drillster/drone-volume-cache:latest
    restore: true
    mount:
      - /drone/docker
    # volumes:
    #   - /tmp/drone-cache:/cache

  publish:
    image: plugins/docker:17.12
    repo: andrey01/REDACTED
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    secrets:
      - docker_username
      - docker_password
    storage_path: /drone/docker
    use_cache: true
    when:
      event: [push, tag]
      branch: master

  rebuild_cache:
    image: drillster/drone-volume-cache:latest
    rebuild: true
    mount:
      - /drone/docker
    # volumes:
    #   - /tmp/drone-cache:/cache
```

After this is set, Drone will keep the docker image cache under: ``/tmp/drone-cache/<username>/<gitrepo>/1/drone/docker/``

When the ``restore_cache`` job is running, you can spot it is running rsync from ``/cache/<username>/<gitrepo>/1//drone/docker/ `` to ``/drone/docker`` inside the drone pipeline. And the ``/cache`` is mounted from ``host:/tmp/drone-cache`` across the whole pipeline as ``DRONE_VOLUME`` drone-server variable was leveraged.

Snap:

```
# ps auxwwf
...
root       896  0.4  0.0   6216  1532 ?        Ss   21:01   0:00  |       \_ /bin/bash /usr/local/cacher.sh
root       964 30.8  0.1  38192  2320 ?        R    21:01   0:05  |           \_ rsync -aHA --delete /cache/<username>/<gitrepo>/1//drone/docker/ /drone/docker
root       965  4.7  0.0  31720  1816 ?        S    21:01   0:00  |               \_ rsync -aHA --delete /cache/<username>/<gitrepo>/1//drone/docker/ /drone/docker
root       966 45.6  0.1  38116  2356 ?        S    21:01   0:08  |                   \_ rsync -aHA --delete /cache/<username>/<gitrepo>/1//drone/docker/ /drone/docker
...
```

> The docker image caching helped to reduce the build time for one of my repositories from 4m39s to 51s.

## References

- http://plugins.drone.io/drillster/drone-volume-cache/

### Missing documentation

- [This documentation](http://plugins.drone.io/drone-plugins/drone-docker/) does not have ``storage_path`` variable documented for some reason.
-  ``DRONE_VOLUME`` is not reflected in the documentation for some reason.. I have found information about it only [here](https://github.com/drone/drone/issues/1837#issuecomment-306761054) and in the [code](https://github.com/drone/drone/commit/1a6920e822b82e50f3cd452b2122242e1420f06c#diff-a1e14c06700b04b423b787fd33d25b34R96)

FYI: @bradrydzewski

**Comment by kav** [comment]
Worth calling out the OP comment; while caching of build layers would be cool and whatnot a great first step would be caching of external images. Might be worth tilting at that and avoiding the how to cache build layers questions and associated issues for the moment.

**Comment by laszlocph** [comment]
Mounting the layer cache into the plugin is not recommended I think.

Instead, you can use cache-from that is portable even to drone cloud.

```
kind: pipeline
name: default

steps:
  - name: docker-builder
    image: plugins/docker
    settings:
      repo: laszlocloud/cache-from-test
      tags: latest
      cache_from: "laszlocloud/cache-from-test:latest"
      dry_run: true
```

More on this here: https://laszlo.cloud/how-using-cache-from-can-speed-up-your-docker-builds-in-droneci

**Comment by marksteve** [comment]
Got around this by mounting the docker storage path of the plugin to the host:

```yaml
kind: pipeline
name: default

steps:

- name: build
  image: plugins/gcr
  volumes:
  - name: docker-gcr
    path: /var/lib/docker

volumes:
- name: docker-gcr
  host:
    path: /var/lib/docker-gcr
```
