### ISSUE TITLE
push to HTTP repository? 

### ISSUE THREAD

**Issue by mvillarejo** [drone-plugins/drone-docker#184]
Hello,

how easy would be to set a http protocol support for registry push? it uses https and my registry is only http.
```
  publish:
    image: plugins/docker
    repo:  registry:80/mygreatimage
    protocol: http
    tags: [ 1.0 ]
    dockerfile: Dockerfile
```

thanks!
