### ISSUE TITLE
Access drone services from within the Dockerfile build process

### ISSUE THREAD

**Issue by vovimayhem** [drone-plugins/drone-docker#186]
I'm using `drone/drone:0.8` along with the Docker plugin, and I'm kinda stuck with a `Dockerfile` I use to build the app.

This `Dockerfile` runs the app test suite as part of it's build process - relevant fragment shown:

```
# ENV & ARG settings:
ENV RAILS_ENV=test RACK_ENV=test
ARG DATABASE_URL=postgres://postgres:3x4mpl3@postgres:5432/app_test

#  Run the tests:
RUN rails db:setup && rspec
```

The test suite requires a connection to the database, for which I'm including the `postgres` service in the `.drone.yml` file:

```
pipeline:
  app:
    image: plugins/docker
    repo: vovimayhem/example-app
    tags:
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_COMMIT_BRANCH/master/latest}
    compress: true
    secrets: [ docker_username, docker_password ]
    use_cache: true
    build_args:
    - DATABASE_URL=postgres://postgres:3x4mpl3@postgres:5432/app_test

services:
  postgres:
    image: postgres:9-alpine
    environment:
    - POSTGRES_PASSWORD=3x4mpl3
```

But it looks like the services defined in the drone file are not accessible from within the build process:

```
Step 18/36 : RUN rails db:setup && rspec
 ---> Running in 141734ca8f12

could not translate host name "postgres" to address: Name does not resolve
Couldn't create database for {"encoding"=>"unicode", "schema_search_path"=>"partitioning,public", "pool"=>5, "min_messages"=>"log", "adapter"=>"postgresql", "username"=>"postgres", "password"=>"3x4mpl3", "port"=>5432, "database"=>"sibyl_test", "host"=>"postgres"}
rails aborted!
PG::ConnectionBad: could not translate host name "postgres" to address: Name does not resolve
```

Is there any configuration I'm missing out? Or this is a feature not currently present in the plugin?

I know this could be related somehow with the `--network` and/or `--add-host` options from `docker build` command... I could help in case you think we should include this behavior.
