### ISSUE TITLE
Autotag functions does not work correctly

### ISSUE THREAD

**Issue by volker-raschek** [drone-plugins/drone-docker#188]
Hello, 
I write a small go application and drone should build and deploy my image into dockers public repository. 

I would like to use the auto tag function. If I push a git tag `1.0.0` into my repository on gitea, drone does not build, deploy and tag my image correctly on dockers public repository. When I make a normal push, drone upgrade only my image called alpine. But alpine should be my tag suffix. There is no tag value.

Where is the issue in my `.drone.yml`?
```yml
workspace:
  base: /go
  path: src/git.cryptic.systems/volker.raschek/simple-cloud

pipeline:
  build_linux_amd64:
    image: golang:1.10.0
    group: build
    commands:
      - go get -u github.com/jteeuwen/go-bindata/...
      - make build-linux-amd64

  publish_linux_amd64_alpine:
    image: plugins/docker:17.05
    repo: volkerraschek/simple-cloud
    group: release
    auto_tag: true
    auto_tag_suffix: alpine
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
```

Official documentation: http://plugins.drone.io/drone-plugins/drone-docker/
Repository: https://git.cryptic.systems/volker.raschek/simple-cloud
Drone: https://drone.cryptic.systems/volker.raschek/simple-cloud
Docker-Hub: https://hub.docker.com/r/volkerraschek/simple-cloud/tags/

Volker
