### ISSUE TITLE
Is there a way to build but not publish images?

### ISSUE THREAD

**Issue by angristan** [drone-plugins/drone-docker#190]
I'm using the drone-docker plugin to build and push docker images.

However I want to only build on non-master branches.

Here's what I have now:

```yml
pipeline:
  docker-build-publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: angristan/myimage
    tags: [ "latest", "0.10", "0.10.6" ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

pipeline:
  docker-build:
    image: plugins/docker
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      branch:
        exclude: [ master]

```
But it seems the plugin want to publish to a repo anyway: `Error parsing reference: ":latest" is not a valid repository/tag: invalid reference format`
