### ISSUE TITLE
ECR: Error response from daemon: invalid reference format

### ISSUE THREAD

**Issue by Ashtonian** [drone-plugins/drone-docker#199]
Trying to push to AWS with using drone:8.6 and agent:8.4 with the following step: 

```
  # publish-project:
  publish-project:
    image: plugins/ecr,
    dockerfile: ./Dockerfile
    registry: redacted.dkr.ecr.us-east-1.amazonaws.com
    repo: redacted.dkr.ecr.us-east-1.amazonaws.com/duke
    tags: latest
    secrets: [ ecr_access_key, ecr_secret_key ]
    when: 
      local: false
```

The step in the pipeline updates itself to done and it looks successful (green clock) in the UI but the overall build fails with 'Error response from daemon: invalid reference format'. Set `DRONE_DEBUG=true` doesn't reveal anything noteworthy. Any ideas?
