### ISSUE TITLE
When auto_tag is specified, tags is ignored

### ISSUE THREAD

**Issue by gboddin** [drone-plugins/drone-docker#201]
Let's imagine we have the following pipeline : 

```
pipeline:
  push-image:
    image: plugin/docker
    auto_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
```

When auto_tag is set, only the automatic tags will be set, ${DRONE_COMMIT_SHA} will be ignored.

Wouldn't it be better for them to be merged ?
