### ISSUE TITLE
Multiple images based on template

### ISSUE THREAD

**Issue by deitch** [drone-plugins/drone-docker#225]
As discussed in [discourse here](https://discourse.drone.io/t/compile-binaries-publish-multiple-docker-images-one-per-architecture/3851) a common pattern with multiple architectures is to build a binary (if relevant) for multiple architectures and then build an OCI image and push out one per architecture, by differentiating by either image name (e.g. `foo/bar-amd64:1.2.3` and `foo/bar-arm64:1.2.3`) or tag (`foo/bar:1.2.3-amd64` and `foo/bar:1.2.3-arm64`). The tag method has been growing in popularity as that is how docker itself does it (and multiple tags are cheaper and easier to maintain than multiple repos).

Right now, to do this with docker plugin, I need to do the following:

```yml
  publish_arm64:
    image: plugins/docker
    repo: foo/bar
    dockerfile: Dockerfile.linux.arm64
    secrets: [ docker_username, docker_password ]
    tag: [ 1.2.3-arm64 ]
    when:
      branch: master
      event: push

  publish_amd64:
    image: plugins/docker
    repo: foo/bar
    dockerfile: Dockerfile.amd64
    secrets: [ docker_username, docker_password ]
    tag: [ 1.2.3-amd64 ]
    when:
      branch: master
      event: push
```

and repeat for every arch.

I'd like to propose that we have a "for loop" type option where it can (optionally) automatically pick up on a pattern and repeat it in the tag, e.g.:

```yml
  publish_arm64:
    image: plugins/docker
    repo: foo/bar
    dockerfile-pattern: Dockerfile.ARCH
    secrets: [ docker_username, docker_password ]
    tag: [ 1.2.3-ARCH ]
    when:
      branch: master
      event: push
```

The above would find any `Dockerfile.ARCH`, building for each such Dockerfile, and then using the extracted `ARCH` in the tag. E.g. if I had `Dockerfile.amd64` and `Dockerfile.arm64` and `Dockerfile.ppc64le`, then it would build 3 images, tagging the first as `1.2.3-amd64`, the second has `1.2.3-arm64` and the third as `1.2.3-ppc64le`.

I think there might be a better way to flag it or use it, but are we interested in principle? Tell me the go code here isn't too messy and I will be happy to open a PR for it.

Some thoughts/questions to answer:

1. `dockerfile-pattern:` vs just using the usual `dockerfile:` and recognizing `ARCH` as a special capture (like regex does). I am a little concerned that it cuts out someone actually having a dockerfile named `Dockerfile.ARCH`.
2. `ARCH` vs something else to flag it? I don't want to use real regexes here - gets too messy to do in a yml file - but conceptually.
3. Reusing the flag in the tag as `ARCH` vs e.g. `$$ARCH` vs some other indication.
4. Using the `tag:` vs `tag-pattern:`?

I am leaning towards an explicit alternate `dockerfile-pattern` and `tag-pattern` to avoid any real confusion, and then `ARCH` can be used explicitly, but open for input.

Thanks!
