### ISSUE TITLE
Auto tag build fails when tag event has no commit sha (Gogs)

### ISSUE THREAD

**Issue by Beanow** [drone-plugins/drone-docker#229]
The build is trigged by a tag event as you would assume: `username created tag 2.1.5`

However the tag seems to be parsed incorrectly.
Using drone server and agent docker tags: 1.0

```yml
kind: pipeline
name: default

steps:
  - name: unit-test
    image: node:10-alpine
    commands:
      - cd app
      - npm i
      - npm test

  - name: build-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: docker.example.com/example/hello-cicd
      registry: docker.example.com
      auto_tag: true
    when:
      event: [tag]
```

Build image step:

```
+ /usr/local/bin/dockerd --data-root /var/lib/docker
+ /usr/local/bin/docker version
Client: Docker Engine - Community
Version: 18.09.4
API version: 1.39
Go version: go1.10.8
Git commit: d14af54
Built: Wed Mar 27 18:33:40 2019
OS/Arch: linux/amd64
Experimental: false
Server: Docker Engine - Community
Engine:
Version: 18.09.4
API version: 1.39 (minimum version 1.12)
Go version: go1.10.8
Git commit: d14af54
Built: Wed Mar 27 18:41:10 2019
OS/Arch: linux/amd64
Experimental: false
+ /usr/local/bin/docker info
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Server Version: 18.09.4
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
seccomp
Profile: default
Kernel Version: 4.4.0-141-generic
Operating System: Alpine Linux v3.9 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.066GiB
Name: 89c58ca4f20e
ID: ES34:VXSB:3J4S:X3HJ:H4PW:7TS3:HWZX:USBO:NTVB:ZS6R:I7O2:GCAJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
+ /usr/local/bin/docker build --rm=true -f Dockerfile -t . --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date=2019-04-09T19:00:27Z --label org.label-schema.vcs-ref= --label org.label-schema.vcs-url=https://git.example.com/example/hello-cicd.git
invalid argument "" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
time="2019-04-09T19:00:27Z" level=fatal msg="exit status 125" 
```
