### ISSUE TITLE
Using "context" breaks build

### ISSUE THREAD

**Issue by metal3d** [drone-plugins/drone-docker#234]
Hi, 

We are using a repository containing several Dockerfiles in subdirectories. This is the pipeline used on Drone 1.0.0, Kubernetes:

```yaml
kind: pipeline
name: php-s2i

steps:
  - name: s2i
    image: plugins/docker
    settings:
      registry: registry-docker-registry.registry:5000
      repo: registry-docker-registry.registry:5000/smile/php:7-apache-s2i
      insecure: true
      context: ./php/

trigger:
  branch:
    - master
```

The Dockerfile is in "./php" directory. As we've got files to ADD from that directory, we need to change context to ./php (we also tried "php" instead of "./php")

This is the error (anonymized):
```
+ /usr/local/bin/docker build --rm=true -f Dockerfile -t 6110e2bdc9196d462d80f3b472f38215a79c6ba2 ./php/ --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date=2019-06-04T09:57:19Z --label org.label-schema.vcs-ref=6110e2bdc9196d462d80f3b472f38215a79c6ba2 --label org.label-schema.vcs-url=https://XXX/smile/docker-images.git
--
74 | unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /drone/src/Dockerfile: no such file or directory
75 | time="2019-06-04T09:57:19Z" level=fatal msg="exit status 1"
```

It seems that the "context" is not used at all.
