### ISSUE TITLE
Support for --ssh flag

### ISSUE THREAD

**Issue by cleverer** [drone-plugins/drone-docker#236]
Similarly to #189 it would be real great if `--ssh` would be supported. https://github.com/docker/cli/pull/1419

Most probably it would be best to be able to be able to specify a key and known_hosts from Drone secrets.

**Comment by tboerger** [comment]
We are not directly implementing every new shiny docker feature, instead we encourage plugin forks with new features people want to use.

More features, need more testing... And since this plugin is used by nearly any drone instance imho it's more or less some kind of feature freeze.

**Comment by cleverer** [comment]
So you're saying it will never get implemented or not now as it is not yet an established feature?

I do get that it has to be quite stable but also I think this would be quite useful for a lot of people who use drone internally and don't want to make dependencies public.

If I could, I'd already have made a fork and opened a pull request, but unfortunately I can't find any documentation on where to start extending the plugin/it's settings…

I'might however get away by including the necessary steps in my Dockerfile and using `build_args_from_env` according to:
https://discourse.drone.io/t/how-can-i-pass-secrets-as-build-args-to-plugins-docker-drone-0-8/824/2.  
However I'd rather not have to do this, since build args are not considered secure.

**Comment by bradrydzewski** [comment]
I'm not necessarily opposed to supporting more docker features, however, new feature requests should ideally include a target use case. Why do we need this feature? What does it enable that you cannot do today? Why should we spend our time working on this instead of other things?

**Comment by cleverer** [comment]
Well, my use case is a Swift project (specifically Vapor), which had private dependencies. (If you wan't to have a look at it, check it out [here](https://git.damutten.ch/Nicolas/HomeControl/src/commit/b6dda9eb92a1939c714be0bf0defc60df3ae344b).)  
Swift package manager would work fine by having ssh-auth handled by docker, but I doubt it would work by just copying. Right now I'd had to build the target in drone and then copying the binary to the docker image. This would prevent building the Dockerfile standalone or I'd had to maintain multiple Dockerfiles. It would also further complicate the drone config and the Dockerfile and be prone to errors.
My idea would be to just supply drone-docker with ssh-keys via a secret and have it build the Dockerfile independently of any previous steps. This would also improve the reproducibilityand reduce complexity.

As you say @bradrydzewski, I'm using drone as a mere wrapper for the docker build, but I think that is kind of the point of a "publishing" step. I don't think that should be a custom runner… but rather the plugin should be able to build any Dockerfile.
I also think that feature is intended for the exact problem I'm facing and would simplify a lot of projects. (If your unsure what to expect, check out: http://blog.oddbit.com/post/2019-02-24-docker-build-learns-about-secr/.) I think it would also lower the entry hurdle for new users and make it easier to create and maintain drone configs and make the whole platform more powerful.

All that being said, I don't think it would be sensible to implement this right now. I'd rather propose to consider doing this when (or if…) it is a feature supported by standard `docker build`, without having to specifically enable the behaviour.

**Comment by bradrydzewski** [comment]
Thanks for the reply.

We frequently see people that just want this:

```
docker build -t foo .
docker run foo
```

When people try to translate the above into a Drone people we see something like this:

```
steps:
- name: build
  image: plugins/docker
  settings:
    repo: octocat/hello-world
    tags: ${DRONE_COMMIT}
    dry_run: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: test
  image: octocat/hello-world:${DRONE_COMMIT}
  commands:
  - npm run test

- name: publish
  image: plugins/docker
  settings:
    repo: octocat/hello-world
    tags: ${DRONE_COMMIT}
    dry_run: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
  - name: docker
    path: /var/run/docker.sock
```

Drone is simply not optimized for this particular workflow. And they do serious gymnastics to get this working with drone, and run into unexpected issues with dangling images and when trying to mount volumes. Drone is simply not optimized for this kind of workflow.

There are many people that ask why they even need a yaml file and why they cannot just use a Dockerfile. Based on years of support and seeing people struggle trying to use Drone in this matter, I do think we need a custom runner.
