### ISSUE TITLE
add auto_tags depth option

### ISSUE THREAD

**Issue by thomasf** [drone-plugins/drone-docker#237]
We release new versions of multiple minor version images in some builds which means that the `{image}:{major}`  tag randomly switches depending on the last build of any 1.x release series . 

So either `auto_tag` can transform into in addition of being an boolean  option also support a list of version tags or it's own option:

```yml
auto_tag_versions: ['major', 'minor', 'patch']
```

**Comment by bradrydzewski** [comment]
auto_tag is meant to be opinionated and simple. Either you use it as-is or you do not use it at all. There are too many ways to customize tags and if we merge this, we have to merge other requests to customize auto_tag (add branch, commit sha, etc). I think a good compromise would be to allow custom tag logic via an external starlark script that you checkin to your repository. Thoughts @tboerger ?

**Comment by thomasf** [comment]
We also have a related problem with several repositories where we release multiple services from one repo using tag prefixes.

Auto tag cannot handle it tags like `cmd/foobar/1.4.3` or `cmd/foobar/v1.4.3`.

The `.drone.yml` section looks something like this.

```yml
- name: docker/foobar
  image: plugins/docker
  settings:
    repo: dreg.example.com/project/foobar
    dockerfile: contrib/drone/Dockerfile.foobar
  when:
    ref:
    - refs/tags/cmd/foobar/**
```

I could also write a separate drone plugin that can create `.tags` files based on various rules.. Right now each project has some code to handle these things individually but scripting support build into this image would be much more convenient than any other solution.
