### ISSUE TITLE
[BUG] DRONE_COMMIT_SHA IS NULL, docker build error？

### ISSUE THREAD

**Issue by lework** [drone-plugins/drone-docker#238]
When the build image is executed when the tag event occurs, the following error will occur.

pipeline
```
- name: build-prod-image
  image: plugins/docker
  settings:
    dockerfile: ./Dockerfile
    storage_path: /drone/src/docker
    repo: 192.168.77.134:5000/root/demo
    registry: 192.168.77.134:5000
    insecure: true
    tags: ${DRONE_TAG}
  when:
    event:
    - tag
```

Error that occurred
```
+ /usr/local/bin/docker build --rm=true -f ./Dockerfile -t . --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date=2019-07-02T08:40:14Z --label org.label-schema.vcs-ref= --label org.label-schema.vcs-url=http://192.168.77.134:3000/root/demo.git
--
70 | WARNING: bridge-nf-call-iptables is disabled
71 | WARNING: bridge-nf-call-ip6tables is disabled
72 | invalid argument "" for "-t, --tag" flag: invalid reference format
73 | See 'docker build --help'.
74 | time="2019-07-02T08:40:14Z" level=fatal msg="exit status 125"
```

The default value of docker build tag is `commit.sha`, However, but when the tag event, `commit.sha` is none

https://github.com/drone-plugins/drone-docker/blob/2908203dff72a4617da0eec32a3e19eea6449a33/cmd/drone-docker/main.go#L245

**Comment by lework** [comment]
```
- name: build-prod-image
  image: plugins/docker
  commands: 
  - "--commit.sha 123"
  settings:
    dockerfile: ./Dockerfile
    storage_path: /drone/src/docker
    repo: 192.168.77.134:5000/root/demo
    registry: 192.168.77.134:5000
    insecure: true
    tags: ${DRONE_TAG}
  environment:
    DRONE_COMMIT_SHA: tag0000
  when:
    event:
    - tag
```

it's not work.
