### ISSUE TITLE
dockerfile parameter not working  

### ISSUE THREAD

**Issue by neil605164** [drone-plugins/drone-docker#239]
HI~ I set dockerfile value ```./k8s.Dockerfile```, but dockerfile parameter  always use default ```Dockerfile``` to build images

```
  steps:
    name: build-dev-image
    image: plugins/docker
    settings:
      tags: latest
      dockerfile: ./k8s.Dockerfile
```

when i run ``` drone exec ```  , the docker build command show like this 
```
/usr/local/bin/docker build --rm=true -f Dockerfile -t 00000000 . --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date=2019-07-04T02:37:19Z --label org.label-schema.vcs-ref=00000000 --label org.label-schema.vcs-url=
```

```drone version: 0.8```

**Comment by ToastCheng** [comment]
I have the same issue, has it been solved?

**Comment by mhumeSF** [comment]
What error are you receiving?

**Comment by ToastCheng** [comment]
just figured it out, I shouldn't add the `settings` tag in the .drone.yml file.

instead of:
```
pipeline:
  <pipeline_name>:
    name: <name>
    image: plugins/docker
    settings:
      username: <username>
      password: <passwd>
      repo: <repo>
      dockerfile: <path_to_dockerfile>
```

it should be:
```
pipeline:
  <pipeline_name>:
    name: <name>
    image: plugins/docker
    username: <username>
    password: <passwd>
    repo: <repo>
    dockerfile: <path_to_dockerfile>
```
