### ISSUE TITLE
Apply pattern to tags to avoid errors

### ISSUE THREAD

**Issue by bastienbc** [drone-plugins/drone-docker#249]
Hi,

I would like to tag my docker images produced by drone with the git tag: very easy.
Except that our branches are created by Jira, which is based on the name of the feature and looks like this:
`feature/PE-999-a-very-long-and-not-docker-friendly-branch-name`

So obviously docker does not like that because of the `/`, but I would like to have it stripped like this:
`feature-PE-999`

This is can be achieved using a simple sed command:
`s/[/@:]/-/g ; s/\([A-Z]\+-[0-9]\+\)-.*$/\1/`

Now I can do that using my own plugin obviously, but I was wondering if that could be implemented natively into this one, with a specific setting:
```
settings:
  sed: 's/[/@:]/-/g ; s/\([A-Z]\+-[0-9]\+\)-.*$/\1/'

# or
settings:
  sed:
    - 's/[/@:]/-/g'
    - 's/\([A-Z]\+-[0-9]\+\)-.*$/\1/'

# or by using yaml multiline
settings:
  sed: >
    s/[/@:]/-/g
    s/\([A-Z]\+-[0-9]\+\)-.*$/\1/
```

I came across this: https://github.com/rwtodd/Go.Sed

In my opinion if this is to be implemented here, it should be applied on every tag, even with auto_tag, but before auto_tag_suffix.

What do you think?

**Comment by tboerger** [comment]
I'm against adding this complexity. Drone got support for simple replacements on .drone.yml level.

**Comment by bradrydzewski** [comment]
The plugin is able to dynamically read tags from a file, so the recommended solution to this sort of problem is to generate a `.tags` file prior to the plugin step:

```
- name: tag
  image: alpine
  commands:
  - sed ... > .tags

- name: publish
  image: plugins/docker
  settings: ...
```

I am going to close this since the .tags file provides a workaround and since I agree with Thomas that this edge case is out of scope. Note that by design plugins are easy to fork and modify, so if you feel strongly about this feature you always have the option to do so

```
  name: publish
- image: plugins/docker
+ image: bastienbc/docker
```
