### ISSUE TITLE
Invalid repository failure if the github organization is all uppercase

### ISSUE THREAD

**Issue by CoryARamirez** [drone-plugins/drone-docker#250]
Trying to publish an image with the following step:

```
- name: publish
  image: plugins/docker
  settings:
    repo: registry/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    registry: registry
    insecure: true
    custom_dns: ip
    auto_tag: true
  when:
    status:
      - success
    event:
      - tag
```
Returns:

```

Error parsing reference: "registry/UPPERCASE-ORG/repo:1" is not a valid repository/tag: invalid reference format: repository name must be lowercase
--
117 | time="2019-09-03T21:32:30Z" level=fatal msg="exit status 1"
```

Seems odd. Anyway we can at the very least have it checked and converted to lowercase, instead of just flat out failing? This requires me to hardcode the org within my pipeline, and I don't want to do that.
