### ISSUE TITLE
The mirror config seems not works for me.

### ISSUE THREAD

**Issue by XiaoHanChina** [drone-plugins/drone-docker#255]
.drone.yml :
```
...
- name: docker-node
    image: plugins/docker
    settings:
      mirror: http://192.168.1.100:5000
      repo: 192.168.1.100:5000/node
      registry: 192.168.10.100:5000
      tags: ${DRONE_TAG=latest}
      insecure: true
```
drone log:
```
+ /usr/local/bin/dockerd --data-root /var/lib/docker --insecure-registry 192.168.1.100:5000 --registry-mirror  http://192.168.1.100:5000
...
Step 1/10 : FROM thingsboard/openjdk8
latest: Pulling from thingsboard/openjdk8
```
Then I checked my registry, and there is no thingsboard/openjdk8 image in it.
It seems like drone docker still pull images from central hub.
