### ISSUE TITLE
Please document MTU settings

### ISSUE THREAD

**Issue by smnbbrv** [drone-plugins/drone-docker#276]
Hi there,

thank you for a great plugin!

Today I spent several hours with a quite specific issue which I still cannot fully understand. Probably it is about some specific config of the network we use for our cluster.

Actors:
- Kubernetes
- Drone CI & Drone Docker (this) plugin
- Alpine image

Actually, what happens is exactly repeating [this alpine issue](https://github.com/gliderlabs/docker-alpine/issues/307): when I run `apk update` as one of the dockerfile's run command it freezes.

So, decreasing the MTU (I set 1000) solved the issue, however I need to go to the source code to find out there is a setting like that:

```yml
kind: pipeline
type: kubernetes
name: default

steps:
  - name: dockerize
    image: plugins/docker
    settings:
      ...
      mtu: 1000
```

Would be super if the setting gets documented. Thank you!
