### ISSUE TITLE
Just provide pull_image: false within the settings.

### ISSUE THREAD

**Issue by YahuiWong** [drone-plugins/drone-docker#289]
Just provide pull_image: false within the settings.

_Originally posted by @tboerger in https://github.com/drone-plugins/drone-docker/issues/261#issuecomment-627543403_

this is my .drone.yml
```YML
kind: pipeline
type: docker
name: default

steps:
-   name: Deploy-${DRONE_BRANCH}
    image: plugins/docker
    settings:
        registry: registry……
        repo: repo……
        tags: ${DRONE_BRANCH}
        dockerfile: src/Dockerfile
        pull-image: false
        pull: false
```

and this is my activity feed

```+ /usr/local/bin/docker build --rm=true -f src/Dockerfile -t 3e981b7e62a23dea284d4c33fc0e7dce4f7d824c . --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date=2020-07-01T14:48:25Z --label org.label-schema.vcs-ref=3e981b7e62a23dea284d4c33fc0e7dce4f7d824c --label org.label-schema.vcs-
```
--pull=true ?
