### ISSUE TITLE
Target not being observed in GCR

### ISSUE THREAD

**Issue by magicalbanana** [drone-plugins/drone-docker#290]
Looking at the [code](https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-gcr/main.go) it seems that we're not getting the `PLUGIN_TARGET` env var so even if I set this, that configuration is ignored. 

Config: 

```
  - name: build-image-web-app
    image: plugins/gcr
    settings:
      registry: us.gcr.io
      dockerfile: dockerfiles/web-app.Dockerfile
      tags:
        - ${DRONE_TAG:-${DRONE_BRANCH}}
      repo: us.gcr.io/magicalbanana/web_app
      target: production
      json_key:
        from_secret: gcr-creds-container-builder-private-key
    depends_on:
      - slack-notification-start-build-images
    when:
      ref:
        - refs/heads/dev
        - refs/heads/master
        - refs/tags/*
      event:
        - tag
        - deployment
        - push
```

Drone Logs:
```
+ /usr/local/bin/docker build --rm=true -f dockerfiles/web-app.Dockerfile -t 9ab56e3561ee965121a87b7f44da60f92df9d5a3 . --pull=true --target production --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date=2020-07-09T13:42:39Z --label org.label-schema.vcs-ref=9ab56e3561ee965121a87b7f44da60f92df9d5a3 --label org.label-schema.vcs-url=https://github.com/magicalbanana/web-app-portal.git
```
