### ISSUE TITLE
tag - auto replace "/" with "-"

### ISSUE THREAD

**Issue by unfor19** [drone-plugins/drone-docker#293]
Hi,
I looked at https://discourse.drone.io/ and didn't find anything related to this issue. In case this issue was already discussed, then sorry for spamming.

## Use case

I'm using the `plugins/ecr` like this - 

```yaml
  - name: build
    image: plugins/ecr
    settings:
      dockerfile: drone/Dockerfile.arm-v8a
      repo: my_repo
      registry: ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com
      tags:
        - "arm-v8a-r19c-${DRONE_COMMIT:0:8}"
        - "latest-arm-v8a"
        - "latest-${DRONE_BRANCH}-arm-v8a" # <-- The issue
      region: eu-west-1
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
```

## Constraints

If the branch name contains a slash `/` then Docker fails to push, since `/` is not a valid character in a tag name.

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters. [Source](https://docs.docker.com/engine/reference/commandline/tag/#extended-description)

We're using JIRA, and some of our branches' names contain `/`, such as `feature/my-cool-feature`, and we want to tag our images with branch names.

## Offered Solution

Is it possible to automatically replace `/` with `-` as a convention? This way there won't be any issues with pushing images that contain `/`, and we'll still be able to use `/` in JIRA.
