### ISSUE TITLE
Error authenticating: exit status 1

### ISSUE THREAD

**Issue by teemola** [drone-plugins/drone-docker#298]
How to use drone-docker plugins to build my image to a insecure local registry ? 

Here is my part of `.drone.yml` ....
```yaml
  # build dev-image
  - name: build-dev-image
    image: plugins/docker:17.05
    settings:
      username:
        - from_secret: harbor_username
      password:
        - from_secret: harbor_password
      repo: 192.168.8.95/xxxx/cicd-demo-local
      registry: 192.168.8.95          
      tags: latest
      dockerfile: ./Dockerfile
      insecure: true
      debug: true
```

```bash

17.05: Pulling from plugins/docker
--
2 | Digest: sha256:a1ee9f89dfe7093d7e38a740a86c5e8403cf5705876d83b604164b8d4c7de269
3 | Status: Downloaded newer image for plugins/docker:17.05
4 | + /usr/local/bin/dockerd -g /var/lib/docker --insecure-registry 192.168.8.95
5 | time="2020-08-19T03:16:24Z" level=warning msg="the \"-g / --graph\" flag is deprecated. Please use \"--data-root\" instead"
6 | time="2020-08-19T03:16:24.066495500Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
7 | time="2020-08-19T03:16:24.068293700Z" level=info msg="libcontainerd: new containerd process, pid: 24"
8 | time="2020-08-19T03:16:25.106395500Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
9 | time="2020-08-19T03:16:25.107063800Z" level=info msg="Loading containers: start."
10 | time="2020-08-19T03:16:25.108584300Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
11 | time="2020-08-19T03:16:25.109738700Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
12 | time="2020-08-19T03:16:25.110787900Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
13 | time="2020-08-19T03:16:25.173646300Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
14 | time="2020-08-19T03:16:25.219041700Z" level=info msg="Loading containers: done."
15 | time="2020-08-19T03:16:25.251854100Z" level=info msg="Daemon has completed initialization"
16 | time="2020-08-19T03:16:25.251907400Z" level=info msg="Docker daemon" commit=89658be graphdriver=overlay2 version=17.05.0-ce
17 | time="2020-08-19T03:16:25.265338100Z" level=info msg="API listen on /var/run/docker.sock"
18 | time="2020-08-19T03:16:25.334126400Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://192.168.8.95/v2/: dial tcp 192.168.8.95:443: getsockopt: connection refused"
19 | time="2020-08-19T03:16:26Z" level=fatal msg="Error authenticating: exit status 1"


```
Maybe the problem is here: `Get https://192.168.8.95/v2/: dial tcp 192.168.8.95:443: getsockopt: connection refused"`
 `insecure: true` seems not to work ??
Please help.....
