### ISSUE TITLE
Support TLS 1.3

### ISSUE THREAD

**Issue by r3pek** [drone-plugins/drone-docker#310]
Pretty much the same as https://github.com/drone-plugins/drone-matrix/issues/17

Right now, when connection to a TLS 1.3 only server, we get this when cloning the repo:
`fatal: unable to access 'https://************.org/********/docker-ideaspacevr.git/': error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version`

**Comment by ashwilliams1** [comment]
This plugin is a wrapper around docker, which means support for TLS 1.3 needs to be implemented at the docker level. It looks like implementing TLS 1.3 is on the docker roadmap. See https://github.com/moby/moby/issues/40495

**Comment by r3pek** [comment]
@ashwilliams1 the error is actually is in the `git fetch origin +refs/heads/master` command, so, i don't think it's really a "docker" problem.

**Comment by ashwilliams1** [comment]
not sure I follow, since this plugin does not perform a git clone

**Comment by r3pek** [comment]
Hummmm what does then? on drone i mean. It clones the original repo and (this plugin) builds a docker image from it. Was under the impression it was this plugin that did it.

```
kind: pipeline
name: build-docker-image

steps:
    -   name: build-docker-image
        image: plugins/docker
        settings:
            repo: r3pek/ideaspacevr
            username:
                from_secret: docker_username
            password:
                from_secret: docker_password
            when:
                branch: master
                event: push
```

^^ this turns into this:

![image](https://user-images.githubusercontent.com/3050556/100386476-631d9500-301d-11eb-8de5-1823cee19169.png)
