### ISSUE TITLE
$$TAG is not working (drone 0.5)

### ISSUE THREAD

**Issue by nukr** [drone-plugins/drone-docker#71]
I am trying add tag to docker
```yaml
pipeline:
  test:
    image: mhart/alpine-node:6.3.1
    commands:
      - echo hihi
  docker:
    repo: project/repo
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    tag:
      - latest
      - "$${TAG}"
    when:
      event: tag
```

But i got these error message
Is it a bug ?

Error parsing reference: "project/repo:$${TAG}" is not a valid repository/tag
exit status 1
