### ISSUE TITLE
Please mention registry usage example in README

### ISSUE THREAD

**Issue by gintsgints** [drone-plugins/drone-docker#81]
README has mentioned option for private registry publish. 
I had to spend some time, while found out that it requests https:// to be prepended at begining of repository.
So I think for others some example in README would help.

**Comment by bradrydzewski** [comment]
all usage documentation is found in the [DOCS.md](https://github.com/drone-plugins/drone-docker/blob/master/DOCS.md) which is in turn used to auto-generate documentation at https://readme.drone.io/plugins

**Comment by gintsgints** [comment]
Actualy... when I use registry with full url, it tags build with it, and gets error - for flag -t: Error parsing reference: "https://divi.techwares.eu/drone/cete:latest" is not a valid repository/tag

**Comment by gintsgints** [comment]
So why not add registry example in DOCS.md ?

**Comment by bradrydzewski** [comment]
https://github.com/drone-plugins/drone-docker/blob/master/DOCS.md#using-a-custom-registry

**Comment by gintsgints** [comment]
ups.. :+1: 

Many thxs

**Comment by gintsgints** [comment]
This is config what finally worked for me (without image):

```
publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: https://divi.techwares.eu
    repo: divi.techwares.eu/drone/cete
    username: myser
    password: mypassword
    email: myemail@gmail.com
    tag: $$BRANCH
    file: Dockerfile
```
