### ISSUE TITLE
Plugin doesn't have the ability to limit or cleanup old images in the registry

### ISSUE THREAD

**Issue by lgeinert** [drone-plugins/drone-docker#92]
We had to set a max count on the registry itself to accomplish this.

**Comment by bradrydzewski** [comment]
I believe this is something that should either be handled by the registry or an external tool. There are some open issues and a variety of different third party tools that can be used:
https://github.com/docker/docker-registry/issues/1004
https://github.com/docker/docker-registry/labels/delete

Alternatively you could create a custom plugin that purges old images from the Docker registry based on whatever retention logic and parameters make sense for your organization. You could run this after the docker plugin in your yaml:

```
pipeline:
  publish:
    image: plugins/docker
    ...

  cleanup:
    image: some-custom-plugin/docker-cleanup
    .... some logic ....
```

So while I definitely recognize the issue you are facing, plugins are meant to do one thing and do it well. For this reason if you need to purge images as part of your build workflow I would recommend doing so in a separate plugin.
